# Generated by Django 5.1.5 on 2025-01-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="returnrequest",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
