# Generated by Django 5.1.5 on 2025-01-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_returnrequest_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="returnrequest",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
