# Generated by Django 5.1.5 on 2025-01-24 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_returnrequest_quantity_returnrequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="returnrequest",
            name="purchase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.purchase"
            ),
        ),
    ]
