# Generated by Django 5.1.5 on 2025-01-25 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_returnrequest_purchase"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchase",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="returnrequest",
            options={"ordering": ["-created_at"]},
        ),
    ]
