# Generated by Django 5.1.5 on 2025-01-29 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_purchase_options_alter_returnrequest_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
